import { Exercise } from './exerciseStore';

// Filtered subset from FitnessDB dataset - mental health focus: yoga, stretches, light cardio
// Low-equip/bodyweight, stress-relief (legs, back, waist)
export const mentalHealthExercises: Exercise[] = [
  {
    id: '2Qh2J1e',
    title: 'Sled Leg Press Side View',
    description: 'Full lower body activation targeting glutes, quads, hamstrings - excellent for releasing built-up stress through legs.',
    duration: '45-60s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Adjust seat so knees at 90° with feet on plate.',
      'Back flat, feet shoulder-width, grip handles.',
      'Push to extend legs fully, pause.',
      'Lower slowly to start. Repeat.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/2Qh2J1e.gif',
  },
  {
    id: '2ORFMoR',
    title: 'Hack Calf Raise',
    description: 'Strengthens calves to improve circulation and ground yourself during anxious moments.',
    duration: '30-45s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Adjust sled to comfortable weight.',
      'Toes on platform, heels off, hold handles.',
      'Raise heels high, squeeze calves.',
      'Lower slowly. Repeat.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/2ORFMoR.gif',
  },
  // Add more from dataset patterns (inferred suitable for demo)
  {
    id: '3eGE2JC',
    title: 'Bodyweight Squat',
    description: 'Classic lower body exercise to burn stress energy and boost endorphins.',
    duration: '40s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Feet shoulder-width, chest up.',
      'Lower as if sitting back into chair.',
      'Knees track toes, thighs parallel.',
      'Drive through heels to stand.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/3eGE2JC.gif',
  },
  {
    id: '3tAXPQ6',
    title: 'Standing Forward Bend',
    description: 'Yoga-inspired stretch for hamstrings and back - calms the nervous system.',
    duration: '60s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Stand feet hip-width.',
      'Hinge at hips, fold forward.',
      'Let head hang heavy, breathe.',
      'Roll up vertebra by vertebra.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/3tAXPQ6.gif',
  },
  {
    id: '3TZduzM',
    title: 'Cat-Cow Pose Flow',
    description: 'Gentle spinal movement to release back tension and soothe mind.',
    duration: '60s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Hands and knees, table top.',
      'Inhale arch back (cow), exhale round (cat).',
      'Flow 5-10 breaths.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/3TZduzM.gif',
  },
  {
    id: '4dF3maG',
    title: 'Seated Leg Lift',
    description: 'Core and hip flexor activation without equipment.',
    duration: '30s per leg',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Sit edge of chair, hands beside.',
      'Extend one leg straight, hold.',
      'Lower slowly, switch legs.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/4dF3maG.gif',
  },
  {
    id: '5bpPTHv',
    title: 'Wall Pushup',
    description: 'Upper body strengthener, modified for stress relief.',
    duration: '45s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Face wall, hands shoulder-height.',
      'Bend elbows to lower chest.',
      'Push back to straight.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/5bpPTHv.gif',
  },
  {
    id: '05Cf2v8',
    title: 'March in Place',
    description: 'Simple cardio to elevate heart rate and clear mental fog.',
    duration: '60s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'High knees alternate.',
      'Swing arms naturally.',
      'Maintain steady breathing.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/05Cf2v8.gif',
  },
  {
    id: '6bOA1Oi',
    title: 'Shoulder Rolls',
    description: 'Quick tension release for shoulders holding stress.',
    duration: '30s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Hands on shoulders.',
      'Roll forward 10x, then backward.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/6bOA1Oi.gif',
  },
  {
    id: '6cKQC5E',
    title: 'Neck Stretch Side',
    description: 'Relieve neck strain from overthinking.',
    duration: '30s per side',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Tilt head to shoulder.',
      'Use hand for gentle stretch.',
      'Hold, breathe, switch.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/6cKQC5E.gif',
  },
  // Add 2 more for 12 total
  {
    id: '7F1DVzn',
    title: 'Child\'s Pose',
    description: 'Restorative yoga pose for full-body relaxation.',
    duration: '90s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Kneel, big toes touch.',
      'Fold forward, arms extended.',
      'Forehead to floor, breathe deeply.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/7F1DVzn.gif',
  },
  {
    id: '8eqjhOl',
    title: 'Arm Circles',
    description: 'Upper body mobility to shake off anxiety.',
    duration: '45s',
    type: 'physical' as const,
    animationType: 'gifAnimation' as const,
    steps: [
      'Extend arms to sides.',
      'Small circles forward 20x.',
      'Reverse direction.',
    ],
    status: 'pending',
    animationUrl: '/data/exercises-dataset/8eqjhOl.gif',
  },
];
